//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectDiemDanh.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL
    {
        public int C_id { get; set; }
        public string C_tieuDe { get; set; }
        public Nullable<int> C_maNguoiGui { get; set; }
        public Nullable<int> C_maNguoiNhan { get; set; }
        public string C_noiDung { get; set; }
        public string C_loaiThu { get; set; }
        public Nullable<System.DateTime> C_ngay { get; set; }
    }
}
