//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectDiemDanh.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOIKHOABIEU
    {
        public int C_id { get; set; }
        public Nullable<int> C_stt { get; set; }
        public Nullable<int> C_thu { get; set; }
        public Nullable<System.DateTime> C_ngayBatDau { get; set; }
        public Nullable<System.DateTime> C_ngayKetThuc { get; set; }
        public Nullable<int> C_idGV_MH { get; set; }
        public Nullable<int> C_idLop { get; set; }
        public Nullable<int> C_idPhong { get; set; }
    }
}
