//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN_MONHOC
    {
        public int C_id { get; set; }
        public Nullable<int> C_stt { get; set; }
        public Nullable<int> C_maGV { get; set; }
        public Nullable<int> C_idMH_HK { get; set; }
    }
}
