//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAPHIEUDIEM_SINHVIEN
    {
        public int id { get; set; }
        public int masv { get; set; }
        public string tensv { get; set; }
        public string tenmh { get; set; }
        public Nullable<decimal> diem { get; set; }
        public Nullable<int> sotc { get; set; }
    }
}
