//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_DIEM
    {
        public int C_masv { get; set; }
        public Nullable<int> C_tinhtrang { get; set; }
        public Nullable<int> C_hocki { get; set; }
        public Nullable<int> C_namhoc { get; set; }
    }
}
