//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public int C_mssv { get; set; }
        public Nullable<int> C_userId { get; set; }
        public string C_heDaoTao { get; set; }
        public Nullable<System.DateTime> C_ngayBatDau { get; set; }
        public string C_trangThai { get; set; }
        public Nullable<int> C_maLop { get; set; }
        public Nullable<bool> C_daXoa { get; set; }
    }
}
