//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int C_userId { get; set; }
        public string C_username { get; set; }
        public string C_email { get; set; }
        public string C_sdt { get; set; }
        public string C_cmnd { get; set; }
        public Nullable<System.DateTime> C_ngaysinh { get; set; }
        public string C_diachi { get; set; }
        public Nullable<int> C_loaiUS { get; set; }
        public Nullable<bool> C_daXoa { get; set; }
    }
}
