//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANTAY
    {
        public int C_id { get; set; }
        public Nullable<int> C_userID { get; set; }
        public string C_maVanTay { get; set; }
        public Nullable<System.DateTime> C_ngayTao { get; set; }
        public Nullable<bool> C_daXoa { get; set; }
        public string C_url { get; set; }
    }
}
