//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectDiemDanh
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCKY
    {
        public int C_id { get; set; }
        public string C_tenHocKy { get; set; }
        public Nullable<int> C_nam { get; set; }
    }
}
