//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_16HCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int C_id { get; set; }
        public string C_username { get; set; }
        public string C_password { get; set; }
        public int C_userId { get; set; }
        public Nullable<System.DateTime> C_ngayLap { get; set; }
    }
}
