//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_16HCB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Project_16HCB_CSDLEntities : DbContext
    {
        public Project_16HCB_CSDLEntities()
            : base("name=Project_16HCB_CSDLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<DIEM> DIEMs { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIENs { get; set; }
        public virtual DbSet<GIAOVIEN_MONHOC> GIAOVIEN_MONHOC { get; set; }
        public virtual DbSet<HOCKY> HOCKies { get; set; }
        public virtual DbSet<KETQUADIEMDANH> KETQUADIEMDANHs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LOPHOC> LOPHOCs { get; set; }
        public virtual DbSet<MAIL> MAILs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<MONHOC_HOCKY> MONHOC_HOCKY { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<VANTAY> VANTAYs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> ConverUserIDToMSSV(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ConverUserIDToMSSV", useridParameter);
        }
    
        public virtual ObjectResult<GetDanhSachHP_Result> GetDanhSachHP(Nullable<int> mSSV)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDanhSachHP_Result>("GetDanhSachHP", mSSVParameter);
        }
    
        public virtual ObjectResult<GetInfoDiemDanh_Result> GetInfoDiemDanh(Nullable<int> mSSV, Nullable<int> maTKB)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            var maTKBParameter = maTKB.HasValue ?
                new ObjectParameter("MaTKB", maTKB) :
                new ObjectParameter("MaTKB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoDiemDanh_Result>("GetInfoDiemDanh", mSSVParameter, maTKBParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> kiemtraSVTonTai(Nullable<int> mSSV)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("kiemtraSVTonTai", mSSVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_dangKyTK(string username, string email, string sdt, string cmnd, Nullable<System.DateTime> ngaysinh, string diachi, Nullable<int> loaiUS, string password_email)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var loaiUSParameter = loaiUS.HasValue ?
                new ObjectParameter("loaiUS", loaiUS) :
                new ObjectParameter("loaiUS", typeof(int));
    
            var password_emailParameter = password_email != null ?
                new ObjectParameter("password_email", password_email) :
                new ObjectParameter("password_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_dangKyTK", usernameParameter, emailParameter, sdtParameter, cmndParameter, ngaysinhParameter, diachiParameter, loaiUSParameter, password_emailParameter);
        }
    
        public virtual ObjectResult<sp_getKhoa_Result> sp_getKhoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getKhoa_Result>("sp_getKhoa");
        }
    
        public virtual ObjectResult<sp_getLopHoc_Result> sp_getLopHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLopHoc_Result>("sp_getLopHoc");
        }
    
        public virtual ObjectResult<sp_getThongTinSinhVien_Result> sp_getThongTinSinhVien(Nullable<int> mSSV)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getThongTinSinhVien_Result>("sp_getThongTinSinhVien", mSSVParameter);
        }
    
        public virtual int sp_getVanTay(string maVantay)
        {
            var maVantayParameter = maVantay != null ?
                new ObjectParameter("maVantay", maVantay) :
                new ObjectParameter("maVantay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getVanTay", maVantayParameter);
        }
    
        public virtual int sp_guiMail(Nullable<int> userID, string irecipients, string isubject, string ibody)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var irecipientsParameter = irecipients != null ?
                new ObjectParameter("irecipients", irecipients) :
                new ObjectParameter("irecipients", typeof(string));
    
            var isubjectParameter = isubject != null ?
                new ObjectParameter("isubject", isubject) :
                new ObjectParameter("isubject", typeof(string));
    
            var ibodyParameter = ibody != null ?
                new ObjectParameter("ibody", ibody) :
                new ObjectParameter("ibody", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guiMail", userIDParameter, irecipientsParameter, isubjectParameter, ibodyParameter);
        }
    
        public virtual int sp_themBangMail(string tieuDe, Nullable<int> maNguoiGui, Nullable<int> maNguoiNhan, string noiDung, string loaiThu)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("tieuDe", tieuDe) :
                new ObjectParameter("tieuDe", typeof(string));
    
            var maNguoiGuiParameter = maNguoiGui.HasValue ?
                new ObjectParameter("maNguoiGui", maNguoiGui) :
                new ObjectParameter("maNguoiGui", typeof(int));
    
            var maNguoiNhanParameter = maNguoiNhan.HasValue ?
                new ObjectParameter("maNguoiNhan", maNguoiNhan) :
                new ObjectParameter("maNguoiNhan", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("noiDung", noiDung) :
                new ObjectParameter("noiDung", typeof(string));
    
            var loaiThuParameter = loaiThu != null ?
                new ObjectParameter("loaiThu", loaiThu) :
                new ObjectParameter("loaiThu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_themBangMail", tieuDeParameter, maNguoiGuiParameter, maNguoiNhanParameter, noiDungParameter, loaiThuParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_themKetQuaDiemDanh(Nullable<int> maUser, Nullable<int> maMH, Nullable<int> maPhong, Nullable<int> loaiUS)
        {
            var maUserParameter = maUser.HasValue ?
                new ObjectParameter("maUser", maUser) :
                new ObjectParameter("maUser", typeof(int));
    
            var maMHParameter = maMH.HasValue ?
                new ObjectParameter("maMH", maMH) :
                new ObjectParameter("maMH", typeof(int));
    
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            var loaiUSParameter = loaiUS.HasValue ?
                new ObjectParameter("loaiUS", loaiUS) :
                new ObjectParameter("loaiUS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_themKetQuaDiemDanh", maUserParameter, maMHParameter, maPhongParameter, loaiUSParameter);
        }
    
        public virtual ObjectResult<sp_timkiemThongTinSinhVien_Result> sp_timkiemThongTinSinhVien(string kEYSEARCH, Nullable<int> sCHOOLCLASSID, Nullable<int> dIVIONID, Nullable<int> gETFINGER, Nullable<int> pAGEINDEX, Nullable<int> pAGESIZE)
        {
            var kEYSEARCHParameter = kEYSEARCH != null ?
                new ObjectParameter("KEYSEARCH", kEYSEARCH) :
                new ObjectParameter("KEYSEARCH", typeof(string));
    
            var sCHOOLCLASSIDParameter = sCHOOLCLASSID.HasValue ?
                new ObjectParameter("SCHOOLCLASSID", sCHOOLCLASSID) :
                new ObjectParameter("SCHOOLCLASSID", typeof(int));
    
            var dIVIONIDParameter = dIVIONID.HasValue ?
                new ObjectParameter("DIVIONID", dIVIONID) :
                new ObjectParameter("DIVIONID", typeof(int));
    
            var gETFINGERParameter = gETFINGER.HasValue ?
                new ObjectParameter("GETFINGER", gETFINGER) :
                new ObjectParameter("GETFINGER", typeof(int));
    
            var pAGEINDEXParameter = pAGEINDEX.HasValue ?
                new ObjectParameter("PAGEINDEX", pAGEINDEX) :
                new ObjectParameter("PAGEINDEX", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_timkiemThongTinSinhVien_Result>("sp_timkiemThongTinSinhVien", kEYSEARCHParameter, sCHOOLCLASSIDParameter, dIVIONIDParameter, gETFINGERParameter, pAGEINDEXParameter, pAGESIZEParameter);
        }
    
        public virtual ObjectResult<sp_xemThoiKhoaBieu_Result> sp_xemThoiKhoaBieu(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_xemThoiKhoaBieu_Result>("sp_xemThoiKhoaBieu", userIdParameter);
        }
    
        public virtual int usp_kiemTraUserDaXoa(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_kiemTraUserDaXoa", useridParameter);
        }
    
        public virtual ObjectResult<usp_layDanhSachMonHoc_Result> usp_layDanhSachMonHoc(ObjectParameter errorMsg)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_layDanhSachMonHoc_Result>("usp_layDanhSachMonHoc", errorMsg);
        }
    
        public virtual ObjectResult<usp_layThongTinMonHocTheoId_Result> usp_layThongTinMonHocTheoId(Nullable<int> monHocId)
        {
            var monHocIdParameter = monHocId.HasValue ?
                new ObjectParameter("monHocId", monHocId) :
                new ObjectParameter("monHocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_layThongTinMonHocTheoId_Result>("usp_layThongTinMonHocTheoId", monHocIdParameter);
        }
    
        public virtual ObjectResult<usp_login_Result> usp_login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_login_Result>("usp_login", usernameParameter, passwordParameter);
        }
    }
}
