//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_16HCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN
    {
        public int C_maGV { get; set; }
        public Nullable<int> C_soNamDay { get; set; }
        public Nullable<int> C_userID { get; set; }
    }
}
