//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_16HCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUADIEMDANH
    {
        public int C_id { get; set; }
        public Nullable<int> C_mssv { get; set; }
        public Nullable<int> C_maMH { get; set; }
        public Nullable<int> C_maPhong { get; set; }
        public Nullable<System.DateTime> C_ngayHoc { get; set; }
    }
}
