//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_16HCB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINTRAPHIEUDIEM
    {
        public int C_masv { get; set; }
        public Nullable<int> C_hocki { get; set; }
        public Nullable<System.DateTime> C_ngaytao { get; set; }
        public Nullable<int> C_magv { get; set; }
    }
}
